name: Smoke Test - PR

on:
  schedule:
    - cron: '0 8 * * 1-5'

jobs:
  RunTest:
    runs-on:  ubuntu-latest

    steps:

      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1.2.0
        with:
          chrome-version: latest

      - name: Instalar ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Rodar o teste
        run: mvn test -Dtest=RunCucumberTest -Dbrowser=chrome-ci -Dcucumber.options="--tags ~@Ignore"

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tests-report
          path: '**/formatedreport/'



